services:
  db:
    image: mariadb:latest
    profiles:
      - dev
    container_name: mariadb_local
    environment:
      - MARIADB_DATABASE=mydb
      - MARIADB_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: ${DOCKERHUB_USERNAME}/user-registry-spring:latest
    container_name: spring_app
    ports:
      - "80:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    restart: always